Add Postfix check, basic logging, answer file

diff --git a/bin/so-email b/bin/so-email
--- a/bin/so-email
+++ b/bin/so-email
@@ -1,26 +1,51 @@
 #!/bin/bash
 #
+# Description:
+# Configure email for Security Onion
+#
 #########################################
 # Variables
 #########################################
 DEBUG="0"
+# Create temp log
+LOG=`mktemp /tmp/so-email.log.XXXXXXXXXX`
+# Get hostname
 HOSTNAME=`hostname`
+# Get IP address of machine
 IP=`ifconfig |grep "inet addr" | awk '{print $2}' |cut -d\: -f2 |grep -v "127.0.0.1" |head -1`
+# Set title for Zenity dialog(s)
 TITLE="Security Onion Email Setup ($HOSTNAME)"
-if [ -f /etc/postfix/main.cf ];then
-	REMOTE=`grep -o 'relayhost =.*' /etc/postfix/main.cf | cut -f2- -d'='| cut -f2 -d' '`
-else
-	REMOTE=''
-fi 
-[ -f /etc/aliases ] && ADMINADDR=`grep -o 'root:.*' /etc/aliases | cut -f2- -d' '`
+# Set 'from' address for mail
 FROMADDRESS="no-reply"
-SOSTATSUMMARY="Not Configured"
-BROSUMMARY="Not Configured"
-OSSECSUMMARY="Not Configured"
-SGUILSUMMARY="Not Configured"
-ELSASUMMARY="Not Configured"
-ELSAUSER="Not Configured"
-ELSASERVER="Not Configured"
+# Daily sostat mail enabled - YES/NO
+SOSTATEMAIL="NO"
+# Default sostat confirmation verbiage
+SOSTATEMAIL_SUMMARY=" - Daily sostat email will not be configured."
+# Bro email enabled - YES/NO
+BROEMAIL="NO"
+# Default Bro confirmation verbiage
+BROEMAIL_SUMMARY=" - Bro email will not be configured."
+# OSSEC email enabled - YES/NO
+OSSECEMAIL="NO"
+# Default OSSEC confirmation verbiage
+OSSECEMAIL_SUMMARY=" - OSSEC email will not be configured"
+# Sguil email enabled - YES/NO
+SGUILEMAIL="NO"
+# Default Sguil confirmation verbiage
+SGUILEMAIL_SUMMARY=" - Sguil email will not be configured."
+# ELSA email enabled - YES/NO
+ELSAEMAIL="NO"
+# Default ELSA confirmation verbiage
+ELSAEMAIL_SUMMARY=" - ELSA email will not be configured."
+# Get notification address from /etc/aliases if it already exists
+[ -f /etc/aliases ] && ADMINADDR=`grep -o 'root:.*' /etc/aliases | cut -f2- -d' '`
+# Get SMTP server from main.cf if it already exists
+if [ -f /etc/postfix/main.cf ];then
+	SMTP=`grep -o 'relayhost =.*' /etc/postfix/main.cf | cut -f2- -d'='| cut -f2 -d' '`
+else
+	SMTP=''
+fi 
+
 #########################################
 # Got r00t?
 #########################################
@@ -29,6 +54,8 @@ if [[ $(/usr/bin/id -u) -ne 0 && "$1" != "-w" ]]; then
     zenity --error --title "$TITLE" --text="Email Setup needs to be run as root.  Please try again using sudo."
     exit
 fi
+
+function ask() {
 #########################################
 # Welcome Screen
 #########################################
@@ -36,7 +63,7 @@ TEXT="<b>Welcome to Security Onion Email Setup!</b>\n\
 \n\
 This program will allow you to configure email for Security Onion on $HOSTNAME.\n\
 \n\
-Please note, this script will install mailutils if it is not already installed.
+Please note, this script will install mailutils and Postfix if they are not already installed.
 \n\
 Would you like to continue?"
 YES="Yes, Continue!"
@@ -88,6 +115,7 @@ while [ $NOTIFY_CONFIRMED = "no" ]; do
                 else
                         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring notification address."
 			NOTIFY_CONFIRMED="yes"
+			NOTIFY_SUMMARY=" - Notification address will be set to: $NOTIFYADDRESS"
                 fi
 	fi
 done
@@ -97,7 +125,7 @@ done
 MAILSERVER_CONFIRMED="no"
 while [ $MAILSERVER_CONFIRMED = "no" ]; do
 	TEXT="What address would you like to specify for the mail (SMTP) server?"
-	MAILSERVER=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$REMOTE"`
+	MAILSERVER=`zenity --title="$TITLE" --text="$TEXT" --entry --entry-text="$SMTP"`
 	ANSWER="$?"
 	if [ $ANSWER -eq 1 ]; then
         	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Exiting Setup"
@@ -108,6 +136,7 @@ while [ $MAILSERVER_CONFIRMED = "no" ]; do
                 else
                         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring SMTP server."
 			MAILSERVER_CONFIRMED="yes"
+			MAILSERVER_SUMMARY=" - Mail (SMTP) server set to: $MAILSERVER"
                 fi
 	fi
 done
@@ -123,9 +152,9 @@ if [ $ANSWER -eq 1 ]; then
         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked No.  Not configuring email for sostat output."
 else
         [  $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring sostat email."
-	SOSTAT_CONFIRMED="yes"
 	SOSTATADDRESS="root@localhost"
-	SOSTATSUMMARY="Configured"
+	SOSTATEMAIL="YES"
+	SOSTATEMAIL_SUMMARY=" - Daily sostat email will be configured."
 fi
 #########################################
 # Bro email
@@ -141,7 +170,8 @@ if [[ $SENSOR -eq 1 ]];then
 	else
         	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for Bro."
 		BROADDRESS="root@localhost"
-		BROSUMMARY="Configured"
+		BROEMAIL="YES"
+		BROEMAIL_SUMMARY=" - Bro email will be configured."
 	fi
 fi
 #########################################
@@ -158,7 +188,8 @@ if [[ $SERVER -eq 1 ]];then
 	else
         	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for Sguil."
 		SGUILADDRESS="root@localhost"
-		SGUILSUMMARY="Configured"
+		SGUILEMAIL="Configured"
+		SGUILEMAIL_SUMMARY=" - Sguil email will be configured."
 	fi
 fi
 #########################################
@@ -174,7 +205,8 @@ if [ $ANSWER -eq 1 ]; then
 else
         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for OSSEC."
 	OSSECADDRESS="root@localhost"
-	OSSECSUMMARY="Configured"
+	OSSECEMAIL="YES"
+	OSSECEMAIL_SUMMARY=" - OSSEC email will be configured."
 fi
 #########################################
 #ELSA email
@@ -190,7 +222,7 @@ if [[ $SERVER -eq 1 ]];then
 	else
         	[ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuring email for ELSA."
 		ELSAADDRESS="root@localhost"
-		ELSASUMMARY="Configured"
+		ELSAEMAIL="YES"
         	ELSA_USER_CONFIRMED="no"
 		while [ $ELSA_USER_CONFIRMED = "no" ]; do	
 			TEXT="What is the ELSA username to which this email address is associated?"
@@ -207,7 +239,7 @@ if [[ $SERVER -eq 1 ]];then
 					ELSA_USER_CONFIRMED="yes"
                 		fi
 			fi
-        	done
+		done
 		#########################################
 		# ELSA server IP/Hostname
         	#########################################
@@ -228,6 +260,7 @@ if [[ $SERVER -eq 1 ]];then
                 		fi
 			fi
 		done
+	ELSAEMAIL_SUMMARY=" - ELSA email will be configured.\n\   - ELSA User: $ELSAUSER\n\   - ELSA Server: $ELSASERVER"
 	fi
 fi
 #########################################
@@ -235,16 +268,14 @@ fi
 #########################################
 TEXT="The following will be configured for $HOSTNAME:\n\
 \n\
-<b>Notification address</b>: $NOTIFYADDRESS\n\
-<b>Mail server</b>: $MAILSERVER\n\
-<b>Daily sostat email</b>:$SOSTATSUMMARY\n\
-<b>Bro email</b>:$BROSUMMARY\n\
-<b>Sguil email</b>:$SGUILSUMMARY\n\
-<b>OSSEC email</b>:$OSSECSUMMARY\n\
-<b>ELSA email</b>:$ELSASUMMARY\n\
-<b>ELSA username</b>: $ELSAUSER\n\
-<b>ELSA server</b>: $ELSASERVER\n\
-\n\Please note, services will restart upon confirmation."
+$NOTIFY_SUMMARY\n\
+$MAILSERVER_SUMMARY\n\
+$SOSTATEMAIL_SUMMARY\n\
+$BROEMAIL_SUMMARY\n\
+$SGUILEMAIL_SUMMARY\n\
+$OSSECEMAIL_SUMMARY\n\
+$ELSAEMAIL_SUMMARY\n\\n\
+Please note, services will restart upon confirmation."
 
 YES="Yes, Continue!"
 NO="No, Quit."
@@ -256,6 +287,13 @@ if [ $ANSWER -eq 1 ]; then
 else
         [ $DEBUG -eq 1 ] && echo "DEBUG: Clicked Yes.  Configuration confirmed."
 fi
+}
+
+function MOVELOG() {
+# Move log file from /tmp/ to /var/log/nsm/
+mv $LOG /var/log/nsm/so-email.log
+LOG="/var/log/nsm/so-email.log"
+}
 
 #########################################
 # Begin function CONFIGURE_EMAIL
@@ -266,11 +304,15 @@ function CONFIGURE_EMAIL() {
 if dpkg -l | grep -q -i "mailutils"; then
         :
 else
-	apt-get install -y mailutils > /dev/null 2>&1
+	apt-get install -y mailutils >> $LOG 2>&1
 fi
-
+if dpkg -l | grep -q -i "postfix"; then
+	:
+else
+	apt-get install -y postfix >> $LOG 2>&1
+fi
 echo "10"
-echo "# Configuring system mail..."
+echo "# Configuring system mail..." | tee -a $LOG
 #Configure system 'notification' address
 ALIASES="/etc/aliases"
 if  grep -q "root:" $ALIASES;then
@@ -278,28 +320,27 @@ if  grep -q "root:" $ALIASES;then
 else
         sed -i "/postmaster/a root: $NOTIFYADDRESS" $ALIASES
 fi
-newaliases > /dev/null 2>&1
+newaliases >> $LOG 2>&1
 #Configure system from address
 POSTFIX="/etc/postfix/main.cf"
 #Configure system mail server
 sed -i "s|^relayhost = .*$|relayhost = $MAILSERVER|g" $POSTFIX
-#Configure loopback-only so that Posfix listens to localhost only
 sed -i "s|^inet_interfaces = .*$|inet_interfaces = loopback-only|g" $POSTFIX
-service postfix restart > /dev/null 2>&1
+service postfix restart >> $LOG 2>&1
 #Configure sostat
-echo "15"
-echo "# Configuring sostat mail..."
-if ! [[ "$SOSTATSUMMARY" == "Not Configured" ]]; then
+if ! [[ "$SOSTATEMAIL" == "NO" ]]; then
+	echo "15"
+	echo "# Configuring sostat mail..." | tee -a $LOG
 	SOSTAT="/etc/cron.d/sostat"
 	touch $SOSTAT
 	echo -e '#/etc/cron.d/sostat\n#\n#crontab entry to run sostat and email its output\n\n\nSHELL=/bin/sh\nPATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin\nEMAIL=root@localhost\nHOSTNAME='$HOSTNAME'\n\n01 12 * * * root /usr/bin/sostat 2>&1 | mail -aFrom:SecurityOnion@$HOSTNAME -s "Statistics for $HOSTNAME" $EMAIL' > $SOSTAT
 fi
 #Configure Bro
-echo "30"
-echo "# Configuring Bro email..."
-if ! [[ "$BROSUMMARY" == "Not Configured" ]]; then
+if ! [[ "$BROEMAIL" == "NO" ]]; then
+	echo "30"
+	echo "# Configuring Bro email..." | tee -a $LOG
 	BROCTL="/opt/bro/etc/broctl.cfg"
-	sed -i "s|^MailTo.*$|MailTo = $BROADDRESS|g" $BROCTL
+	sed -i "s|^MailTo.*$|MailTo = root@localhost|g" $BROCTL
         if grep -q "tracesummary=" $BROCTL;then
         	sed -i "s|^tracesummary=.*$|tracesummary=|g" $BROCTL
 	else
@@ -311,25 +352,23 @@ if ! [[ "$BROSUMMARY" == "Not Configured" ]]; then
         else
         	echo -e "\n# Bro Notice email configuration\nhook Notice::policy(n: Notice::Info)\n             {       \n      add n\$actions[Notice::ACTION_ALARM];\n         }" >> $LOCALBRO
         fi
-	nsm_sensor_ps-restart --only-bro > /dev/null
+	nsm_sensor_ps-restart --only-bro >> $LOG 2>&1
 fi
 #Configure Sguil
-echo "45"
-echo "# Configuring Sguil email..."
-if ! [[ "$SGUILSUMMARY" == "Not Configured" ]]; then
-
+if ! [[ "$SGUILEMAIL" == "NO" ]]; then
+	echo "45"
+	echo "# Configuring Sguil email..." | tee -a $LOG
 	SGUILDEMAIL="/etc/nsm/securityonion/sguild.email"
 	sed -i "s|^set EMAIL_EVENTS.*$|set EMAIL_EVENTS 1|g" $SGUILDEMAIL
         sed -i "s|^set SMTP.*$|set SMTP_SERVER localhost|g" $SGUILDEMAIL
         sed -i "s|^set EMAIL_RCPT.*$|set EMAIL_RCPT_TO \"root@localhost\"|g" $SGUILDEMAIL
         sed -i "s|^set EMAIL_FROM.*$|set EMAIL_FROM \"Sguil\"|g" $SGUILDEMAIL
-	nsm_server_ps-restart > /dev/null
+	nsm_server_ps-restart >> $LOG 2>&1
 fi
-echo $FROMADDRESS
 #Configure OSSEC
-echo "60"
-echo "# Configuring OSSEC email..."
-if ! [[ "$OSSECSUMMARY" == "Not Configured" ]]; then
+if ! [[ "$OSSECEMAIL" == "NO" ]]; then
+	echo "60"
+	echo "# Configuring OSSEC email..." | tee -a $LOG
 	OSSECCONF="/var/ossec/etc/ossec.conf"
         sed -i 's/.*email_notification.*/     <email_notification>yes<\/email_notification>/' $OSSECCONF
 	if grep -q -i "smtp" $OSSECCONF;then
@@ -343,12 +382,12 @@ if ! [[ "$OSSECSUMMARY" == "Not Configured" ]]; then
                 sed -i '/.*smtp_server.*/ a \     <email_from>no-reply<\/email_from>' $OSSECCONF
                 sed -i '/.*email_from.*/ a \     <email_maxperhour>\100\<\/email_maxperhour>' $OSSECCONF
         fi
-	service ossec-hids-server restart > /dev/null
+	service ossec-hids-server restart >> $LOG 2>&1
 fi
 #Configure ELSA
-echo "75"
-echo "# Configuring ELSA email..."
-if ! [[ "$ELSASUMMARY" == "Not Configured" ]]; then
+if ! [[ "$ELSAEMAIL" == "NO" ]]; then
+	echo "75"
+	echo "# Configuring ELSA email..." | tee -a $LOG
 	ELSAWEB="/etc/elsa_web.conf"
 	mysql --defaults-file=/etc/mysql/debian.cnf -Dsecurityonion_db -e "update user_info set email='$ELSAADDRESS' where username='$ELSAUSER';"
         sed -i 's#.*display_address.*#    "display_address": "ELSA@'$HOSTNAME'",#g' $ELSAWEB
@@ -358,15 +397,107 @@ if ! [[ "$ELSASUMMARY" == "Not Configured" ]]; then
         else
                 sed -i '/.*base_url.*/ a \    "smtp_server": "localhost",' $ELSAWEB
         fi
-	service apache2 restart > /dev/null 2>&1
+	service apache2 restart >> $LOG 2>&1
 fi
 }
-CONFIGURE_EMAIL | zenity --progress --title="$TITLE" --text="Please wait while making changes to the system..." --percentage=0 --auto-close
+#########################################
+# Options
+#########################################
+
+usage()
+{
+cat <<EOF
+
+Security Onion Email Setup
+
+     Options:
+
+        -h              This message
+        -f <file>       Configure using answer file <file>
+
+Usage: $0
+EOF
+}
+# Check to see if the user provided an answer file
+while getopts "hf:" OPTION
+do
+     case $OPTION in
+         h)
+                usage
+                exit 0
+                ;;
+         f)
+                ANSWERFILE="$OPTARG"
+                # Verify answer file exists and then read it into memory
+                if [ ! -f "$ANSWERFILE" ]; then
+                        echo "Error accessing $ANSWERFILE"
+                        exit 1
+                fi
+             ;;
+     esac
+done
+
+# GUI (Zenity) or CLI?
+# Default to zenity
+OUTPUT="gui"
+# If no X11, then fall back to cli
+[ -z "$DISPLAY" ] && OUTPUT="cli"
+# If user provided an answer file, set to cli
+[ -f "$ANSWERFILE" ] && OUTPUT="cli"
+# If the user didn't provide an answer file, then ask them the questions
+if [ ! -f "$ANSWERFILE" ]; then
+        if [ "$OUTPUT" = "gui" ] ; then
+                ask
+        else
+                echo
+                echo "No X display found."
+                echo
+                echo "You'll need to either:"
+                echo
+                echo "- use SSH X-forwarding (ssh -X)"
+                echo
+                echo "OR"
+                echo
+                echo "- use an answer file (sudo sosetup -f so-email.conf)"
+                echo
+                usage
+                exit 0
+        fi
+else
+        source "$ANSWERFILE"
+        echo
+        echo "Security Onion Email Setup"
+        echo
+        echo "Ready to configure system using parameters in $ANSWERFILE."
+        echo
+        echo "WARNING! Continuing will destroy any existing email configuration."
+        echo "Are you sure you want to continue?"
+        echo "Type yes to continue or anything else to exit."
+        read INPUT
+        [ "$INPUT" != "yes" ] && exit 0
+        echo
+fi
+
+if [ "$OUTPUT" = "gui" ]; then
+	CONFIGURE_EMAIL |
+	zenity --progress --title="$TITLE" --text="Please wait while making changes to the system..." --percentage=0 --auto-close
+else
+        echo "Please wait while..."
+        CONFIGURE_EMAIL | grep --line-buffered "^#" | sed 's|# Please wait while||g'
+fi
+
+MOVELOG
 ########################################
 # Setup Complete
 ########################################
-TEXT="<b>Security Onion Email Setup is now complete!</b> \n \
-\n \
+TEXT="Security Onion Email Setup is now complete! \n \
+\n\
 If you would like to edit the email configuration manually, please refer to:\n
 https://github.com/Security-Onion-Solutions/security-onion/wiki/Email\n"
-zenity --info --title="$TITLE" --text="$TEXT" --no-wrap
+if [ "$OUTPUT" = "gui" ]; then
+	zenity --info --title="$TITLE" --text="$TEXT" --no-wrap
+else
+	echo
+	echo "$TEXT" | sed 's|\\n|\n|g' | sed 's|\\||g' | tee -a $LOG
+	echo
+fi
